# Generated by Django 5.1.2 on 2024-12-09 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Загрузити фотографию",
                null=True,
                upload_to="product/photo",
                verbose_name="фото",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.IntegerField(
                blank=True,
                help_text="Введите цену",
                max_length=100,
                null=True,
                verbose_name="Цена",
            ),
        ),
    ]
